### ISSUE TITLE
没有可以选择的python环境

### ISSUE THREAD

**Issue by nanarino** [hrpzcf/AwesomePyKit#1]
操作系统 win10 amd64 admin用户 管理员启动
AwesomePyKit 版本0.8.0 解压版
已安装64位python3.9.1安装包
打包工具 选择python环境 没有可选的 是空白

**Comment by hrpzcf** [comment]
抱歉，现在才看到issue，没有可选环境的原因是没有先在"包管理器"中添加Python环境(自动、手动)，包管理器中添加了环境以后，打包工具里才会有可选的环境。本来想把功能彻底分割出来的后来懒了就搁置了 ^_^。
