### ISSUE TITLE
求助一下，软件怎么使用，这是我的报错

### ISSUE THREAD

**Issue by yinhanghang** [hrpzcf/AwesomePyKit#10]
我想用这个打包软件（本项目的发布软件）打包    打包软件的源码(本项目的源码)   失败了

前提：
源码runpykit.py在pycharm可以运行

1.第一个问题，
PyQt5和pyside6冲突
在排除模块，添加  PyQt5，会打包成功，但是运行不了，提示如下
![image](https://github.com/hrpzcf/AwesomePyKit/assets/52708329/bc6eaf19-4e75-4a4e-bc64-6a2f63ba0dba)

完后我删除所有的pyside6模块
2.第二个问题
打包失败，打包提示python停止运行
![image](https://github.com/hrpzcf/AwesomePyKit/assets/52708329/a103f74c-be2e-4c62-816d-b253a4325dbe)
提示信息：
PyInstaller.isolated._parent.SubprocessDiedError: Isolated subprocess crashed while importing package 'settings'! Package import list: ['PyQt5.uic', 'PyQt5.uic.Loader', 'PyQt5.uic.port_v3', 'PyQt5.uic.Compiler', 'PyQt5', 'pkg_resources', 'logging', 'email', 'urllib', 'ctypes', 'packaging', 'http', 'html', 'pydoc_data', 'importlib.metadata', 'pkg_resources._vendor.packaging', 'win32com.shell', 'win32com', 'win32com.client', 'pywin.mfc', 'pywin.dialogs', 'pywin', 'win32com.server', 'pkg_resources._vendor', 'pkg_resources.extern', 'importlib', 'xml.parsers', 'xml', 'xml.sax', '_pyi_rth_utils', 'xmlrpc', 'multiprocessing.dummy', 'multiprocessing', 'collections', 'encodings', 'utils', 'qt_material', 'jinja2', 'markupsafe', 'json', 'asyncio', 'concurrent.futures', 'concurrent', 'xml.etree', 'qt_material.resources', 'xml.dom', 'qdarkstyle', 'qdarkstyle.light', 'qdarkstyle.dark', 'qtpy', 'ui', 'settings', 'res', 'logic', 'chardet', 'com', 'importlib_metadata', 'zipp', 'zipp.compat', 'fastpip', 'fastpip.utils', 'psutil', 'fastpip.core', 'fastpip.com']

好像和settings文件夹有关，

有没有好心人帮帮我

**Comment by hrpzcf** [comment]
运行打包好的 awespykit.exe 来打包 pyqt5 程序是会有一些找不到动态库的问题，推荐使用 pip 向 python 环境安装 awespykit 后，在命令窗口使用 rpk 运行的 awespykit 来打包，或者使用从源代码运行的 awespykit 来打包。

其他一些需要注意的地方：
![屏幕截图 2024-03-18 163839](https://github.com/hrpzcf/AwesomePyKit/assets/58855572/59049b49-ff81-4f8e-a49f-52befb48846d)

**Comment by yinhanghang** [comment]
感谢帮助，我在pycharm的awespykit安装模块后，pycharm启动终端rpk,成功打包了。
非常感谢
