### ISSUE TITLE
用来安装ddddocr时和pip的版本不同

### ISSUE THREAD

**Issue by zdoek001** [hrpzcf/AwesomePyKit#2]
用软件安装始终时1.0.6版本 ，pip安装可以1.4.7.镜像源都是清华

**Comment by hrpzcf** [comment]
是不是安装在同一个环境呢？有时候不同版本的包对 Python 版本要求不同，会出现这种情况。
在控制台输入 pip -V 可以查看当前 pip 是属于哪个环境的。

**Comment by zdoek001** [comment]
同一个环境,而且机子上所有环境都测过.不知道为啥pip安装的不一样的版本.你可以试试.是不是你软件装也是1.0.6&nbsp;pip就是1.4.7 .一样的清华源.不知道哪里出问题了

**Comment by hrpzcf** [comment]
我试了一下，使用 Awespykit 安装 ddddocr，py3.7 和 3.10 都可以安装到最新的 1.4.7 版本，不知道你的 Python 环境是什么版本呢？
![2022-12-26_130756](https://user-images.githubusercontent.com/58855572/209504374-2efccd5b-d074-4df7-a044-76ef1dba4d10.png)

**Comment by zdoek001** [comment]
稍等&nbsp;今晚回去截个图&nbsp;我是3.11
&nbsp;


刘思阳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月26日(星期一) 中午1:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hrpzcf/AwesomePyKit] 用来安装ddddocr时和pip的版本不同 (Issue #2)





 
我试了一下，使用 Awespykit 安装 dddocr，py3.7 和 3.10 都可以安装到最新的 1.4.7 版本，不知道你的 Python 环境是什么版本呢？

**Comment by hrpzcf** [comment]
我去 PyPi 看了一下， ddddocr 对 Python 的版本要求是 < Python 3.11
![2022-12-26_134958](https://user-images.githubusercontent.com/58855572/209508634-74d720ac-ea76-4057-8c8c-7c9460f00990.png)
使用 Python 3.11 实测了一下使用 pip 命令也是没法安装 ddddocr，报错显示 ddddocr 的关键依赖库 onnxruntime 没有支持 Python 3.11 的版本，你之前是不是通过别的办法手动把 ddddocr 的依赖（比如 onnxruntime）安装到环境中的

**Comment by zdoek001** [comment]
可以了，谢谢，不知道为什么昨天搞了一个小时一直都是1.0.6版本。今天直接装就是1.4.7。我有几个环境呢，py3.11也能用的，可能是他没写。软件很好用。感谢开发这个工具。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月26日(周一) 中午1:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hrpzcf/AwesomePyKit] 用来安装ddddocr时和pip的版本不同 (Issue #2)




 
我去 PyPi 看了一下， ddddocr 对 Python 的版本要求是 < Python 3.11
 
 使用 Python 3.11 实测了一下使用 pip 命令也是没法安装 ddddocr，报错显示 ddddocr 的关键依赖库 onnxruntime 没有支持 Python 3.11 的版本，你之前是不是通过别的办法手动把 ddddocr 的依赖（比如 onnxruntime）安装到环境中的

**Comment by zdoek001** [comment]
对的，3.11我有手动放库，昨天我测的环境有3.8和3.11都不行。不知道到底发生了什么。今天又没事了，感谢感谢。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月26日(周一) 中午1:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hrpzcf/AwesomePyKit] 用来安装ddddocr时和pip的版本不同 (Issue #2)




 
我去 PyPi 看了一下， ddddocr 对 Python 的版本要求是 < Python 3.11
 
 使用 Python 3.11 实测了一下使用 pip 命令也是没法安装 ddddocr，报错显示 ddddocr 的关键依赖库 onnxruntime 没有支持 Python 3.11 的版本，你之前是不是通过别的办法手动把 ddddocr 的依赖（比如 onnxruntime）安装到环境中的

**Comment by hrpzcf** [comment]
好的![03200CCE](https://user-images.githubusercontent.com/58855572/209625127-54b3dd21-a6ad-4c6a-bd81-20015a77bb8c.png)
我关闭 Issue 了
