### ISSUE TITLE
本地文件夹镜像仓库如何设置本人电脑上不了网

### ISSUE THREAD

**Issue by lizhuang2511** [hrpzcf/AwesomePyKit#5]

**Comment by hrpzcf** [comment]
参考：https://blog.csdn.net/qq_40442753/article/details/118216399

先决条件是搭建本地源服务器，搭建完成后，首先打开“Pip 源设置工具”，在“编辑地址”输入框输入你搭建的源仓库的本地网络地址，在“编辑名称”输入框随便输入名称，点击“保存到列表”，点击“启用镜像源”就可用生效了。
